import * as THREE from "three";

export type Materials = {
  Habanero: THREE.MeshStandardMaterial;
  ["Opaque(255,255,255)"]: THREE.MeshStandardMaterial;
  Camouflage: THREE.MeshStandardMaterial;
  Himalaya: THREE.MeshStandardMaterial;
  ["Butterfly Garden"]: THREE.MeshStandardMaterial;
  ["Opaque(255,255,192)"]: THREE.MeshStandardMaterial;
  ["Opaque(215,208,192)"]: THREE.MeshStandardMaterial;
  ["Opaque(211,214,211)"]: THREE.MeshStandardMaterial;
  ["Opaque(215,208,192)"]: THREE.MeshStandardMaterial;
  ["Opaque(211,214,211)"]: THREE.MeshStandardMaterial;
  ["Opaque(215,208,192)"]: THREE.MeshStandardMaterial;
  ["Opaque(211,214,211)"]: THREE.MeshStandardMaterial;
  ["Opaque(215,208,192)"]: THREE.MeshStandardMaterial;
  ["Opaque(211,214,211)"]: THREE.MeshStandardMaterial;
  ["Opaque(215,208,192)"]: THREE.MeshStandardMaterial;
  ["Opaque(211,214,211)"]: THREE.MeshStandardMaterial;
  ["Opaque(215,208,192)"]: THREE.MeshStandardMaterial;
  ["Opaque(211,214,211)"]: THREE.MeshStandardMaterial;
  ["Opaque(215,208,192)"]: THREE.MeshStandardMaterial;
  ["Opaque(211,214,211)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  Cleopatra: THREE.MeshStandardMaterial;
  Blaze: THREE.MeshStandardMaterial;
  ["Opaque(255,207,128)"]: THREE.MeshStandardMaterial;
  Bella: THREE.MeshStandardMaterial;
  Aurora: THREE.MeshStandardMaterial;
  Diamond: THREE.MeshStandardMaterial;
  ["Classic Mix"]: THREE.MeshStandardMaterial;
  Infusion: THREE.MeshStandardMaterial;
  ["Pacific Spirit"]: THREE.MeshStandardMaterial;
  Brooklyn: THREE.MeshStandardMaterial;
  Nylon: THREE.MeshStandardMaterial;
  Mikado: THREE.MeshStandardMaterial;
  Santana: THREE.MeshStandardMaterial;
  Zambia: THREE.MeshStandardMaterial;
  ["Cactus Hill"]: THREE.MeshStandardMaterial;
  ["Retro Vibe"]: THREE.MeshStandardMaterial;
  Amulet: THREE.MeshStandardMaterial;
  Karma: THREE.MeshStandardMaterial;
  Landon: THREE.MeshStandardMaterial;
  Belfast: THREE.MeshStandardMaterial;
  Kenya: THREE.MeshStandardMaterial;
  ["Cold Spring"]: THREE.MeshStandardMaterial;
  Allure: THREE.MeshStandardMaterial;
  Zuni: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  Beauty: THREE.MeshStandardMaterial;
  Milton: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  ["Silver Glossy"]: THREE.MeshStandardMaterial;
  ["Opaque(255,207,128)"]: THREE.MeshStandardMaterial;
  ["Magic Moment"]: THREE.MeshStandardMaterial;
  Amelia: THREE.MeshStandardMaterial;
  Tulip: THREE.MeshStandardMaterial;
  ["Delicious Mix"]: THREE.MeshStandardMaterial;
  Pyramid: THREE.MeshStandardMaterial;
  Pluto: THREE.MeshStandardMaterial;
  Excalibur: THREE.MeshStandardMaterial;
  ["Caribbean Beauty"]: THREE.MeshStandardMaterial;
  Kentucky: THREE.MeshStandardMaterial;
  Shelton: THREE.MeshStandardMaterial;
  Turbo: THREE.MeshStandardMaterial;
  ["Cold North"]: THREE.MeshStandardMaterial;
  Milano: THREE.MeshStandardMaterial;
  Kimono: THREE.MeshStandardMaterial;
  Eternity: THREE.MeshStandardMaterial;
  Valencia: THREE.MeshStandardMaterial;
  Havana: THREE.MeshStandardMaterial;
  ["Hidden Place"]: THREE.MeshStandardMaterial;
  ["Morning Rush"]: THREE.MeshStandardMaterial;
  ["Emerald Dream"]: THREE.MeshStandardMaterial;
  ["Coral Garden"]: THREE.MeshStandardMaterial;
  Stanley: THREE.MeshStandardMaterial;
  ["Irish Beauty"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  ["Lucky Day"]: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,207,128)"]: THREE.MeshStandardMaterial;
  ["Garden Glory"]: THREE.MeshStandardMaterial;
  ["Mystic Harbor"]: THREE.MeshStandardMaterial;
  Afternoon: THREE.MeshStandardMaterial;
  ["Gossip Soda"]: THREE.MeshStandardMaterial;
  ["Hawaiian Passion"]: THREE.MeshStandardMaterial;
  Bermuda: THREE.MeshStandardMaterial;
  Aragon: THREE.MeshStandardMaterial;
  ["Force of Nature"]: THREE.MeshStandardMaterial;
  Picasso: THREE.MeshStandardMaterial;
  ["Distant Land"]: THREE.MeshStandardMaterial;
  ["Lunar Dust"]: THREE.MeshStandardMaterial;
  Tuscan: THREE.MeshStandardMaterial;
  Euphoria: THREE.MeshStandardMaterial;
  Valley: THREE.MeshStandardMaterial;
  Skyline: THREE.MeshStandardMaterial;
  ["Plastic_-_Matte_(Black)"]: THREE.MeshStandardMaterial;
  ["Hidden Paradise"]: THREE.MeshStandardMaterial;
  ["Opaque(255,207,128)"]: THREE.MeshStandardMaterial;
  ["Secret Path"]: THREE.MeshStandardMaterial;
  Blair: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,207,128)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,207,128)"]: THREE.MeshStandardMaterial;
  ["Early Glow"]: THREE.MeshStandardMaterial;
  Atoll: THREE.MeshStandardMaterial;
  Adonis: THREE.MeshStandardMaterial;
  Monarch: THREE.MeshStandardMaterial;
  Vera: THREE.MeshStandardMaterial;
  Dallas: THREE.MeshStandardMaterial;
  ["Exotic Life"]: THREE.MeshStandardMaterial;
  Solitaire: THREE.MeshStandardMaterial;
  Berry: THREE.MeshStandardMaterial;
  Nana: THREE.MeshStandardMaterial;
  ["Opaque(128,128,128)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,207,128)"]: THREE.MeshStandardMaterial;
  Arctic: THREE.MeshStandardMaterial;
  ["Fresh Air"]: THREE.MeshStandardMaterial;
  Fiesta: THREE.MeshStandardMaterial;
  Alpine: THREE.MeshStandardMaterial;
  Fantasy: THREE.MeshStandardMaterial;
  Fountain: THREE.MeshStandardMaterial;
  Beluga: THREE.MeshStandardMaterial;
  Incognito: THREE.MeshStandardMaterial;
  ["Quiet Time"]: THREE.MeshStandardMaterial;
  ["Private Tone"]: THREE.MeshStandardMaterial;
  Atlantis: THREE.MeshStandardMaterial;
  ["Duck Hunt"]: THREE.MeshStandardMaterial;
  Jasper: THREE.MeshStandardMaterial;
  ["Exotic Escape"]: THREE.MeshStandardMaterial;
  ["Wild Party"]: THREE.MeshStandardMaterial;
  Warrior: THREE.MeshStandardMaterial;
  ["Secret Garden"]: THREE.MeshStandardMaterial;
  Mars: THREE.MeshStandardMaterial;
  Backlight: THREE.MeshStandardMaterial;
  Andres: THREE.MeshStandardMaterial;
  ["Secret Story"]: THREE.MeshStandardMaterial;
  Kimberly: THREE.MeshStandardMaterial;
  Bastille: THREE.MeshStandardMaterial;
  Cologne: THREE.MeshStandardMaterial;
  Satellite: THREE.MeshStandardMaterial;
  Harlequin: THREE.MeshStandardMaterial;
  ["Gentle Glow"]: THREE.MeshStandardMaterial;
  ["Crazy Eyes"]: THREE.MeshStandardMaterial;
  Romeo: THREE.MeshStandardMaterial;
  ["Royal Vibe"]: THREE.MeshStandardMaterial;
  Medusa: THREE.MeshStandardMaterial;
  Bavarian: THREE.MeshStandardMaterial;
  Ozark: THREE.MeshStandardMaterial;
  Emily: THREE.MeshStandardMaterial;
  Tsunami: THREE.MeshStandardMaterial;
  Solar: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,207,128)"]: THREE.MeshStandardMaterial;
  Hero: THREE.MeshStandardMaterial;
  ["Little Valley"]: THREE.MeshStandardMaterial;
  Denver: THREE.MeshStandardMaterial;
  Retro: THREE.MeshStandardMaterial;
  ["Morning Shine"]: THREE.MeshStandardMaterial;
  Saxon: THREE.MeshStandardMaterial;
  ["Instant Glory"]: THREE.MeshStandardMaterial;
  ["Dizzy Days"]: THREE.MeshStandardMaterial;
  Alexa: THREE.MeshStandardMaterial;
  Aiden: THREE.MeshStandardMaterial;
  Lisa: THREE.MeshStandardMaterial;
  Berlin: THREE.MeshStandardMaterial;
  Kingdom: THREE.MeshStandardMaterial;
  Melbourne: THREE.MeshStandardMaterial;
  ["Hawaii Morning"]: THREE.MeshStandardMaterial;
  Bubble: THREE.MeshStandardMaterial;
  Kashmir: THREE.MeshStandardMaterial;
  ["Horizon Glow"]: THREE.MeshStandardMaterial;
  Phantom: THREE.MeshStandardMaterial;
  ["Island Moment"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Clean Slate"]: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Solid: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Golem: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Diesel: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Alley: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Poetic Charm"]: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Maple View"]: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Eagle Eye"]: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Safari: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Monet: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Nobel: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(192,192,192)"]: THREE.MeshStandardMaterial;
  Orient: THREE.MeshStandardMaterial;
  ["Clear View"]: THREE.MeshStandardMaterial;
  London: THREE.MeshStandardMaterial;
  Azul: THREE.MeshStandardMaterial;
  Madison: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,255,255)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  Godzilla: THREE.MeshStandardMaterial;
  Ballon: THREE.MeshStandardMaterial;
  Bengal: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  ["Quiet Moment"]: THREE.MeshStandardMaterial;
  Corvette: THREE.MeshStandardMaterial;
  Relax: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,255,255)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  Hampton: THREE.MeshStandardMaterial;
  Cupcake: THREE.MeshStandardMaterial;
  Yolanda: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  Niagara: THREE.MeshStandardMaterial;
  ["Timeless Beauty"]: THREE.MeshStandardMaterial;
  ["Caribbean Balm"]: THREE.MeshStandardMaterial;
  ["Opaque(255,255,255)"]: THREE.MeshStandardMaterial;
  Circus: THREE.MeshStandardMaterial;
  Hurricane: THREE.MeshStandardMaterial;
  ["Cozy Cover"]: THREE.MeshStandardMaterial;
  Placebo: THREE.MeshStandardMaterial;
  Jupiter: THREE.MeshStandardMaterial;
  Bizarre: THREE.MeshStandardMaterial;
  Rosemary: THREE.MeshStandardMaterial;
  Manhattan: THREE.MeshStandardMaterial;
  ["Coastal Calm"]: THREE.MeshStandardMaterial;
  ["Simply Elegant"]: THREE.MeshStandardMaterial;
  ["Country Summer"]: THREE.MeshStandardMaterial;
  Nemo: THREE.MeshStandardMaterial;
  ["Historic Shade"]: THREE.MeshStandardMaterial;
  Axel: THREE.MeshStandardMaterial;
  Maverick: THREE.MeshStandardMaterial;
  ["Classic Calm"]: THREE.MeshStandardMaterial;
  ["Day Dream"]: THREE.MeshStandardMaterial;
  ["Island Paradise"]: THREE.MeshStandardMaterial;
  ["Eternal Flame"]: THREE.MeshStandardMaterial;
  ["Crocodile Smile"]: THREE.MeshStandardMaterial;
  Lola: THREE.MeshStandardMaterial;
  Panama: THREE.MeshStandardMaterial;
  Reflection: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,255,255)"]: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(204,209,238)"]: THREE.MeshStandardMaterial;
  ["Simply Delicious"]: THREE.MeshStandardMaterial;
  Abyss: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(204,209,238)"]: THREE.MeshStandardMaterial;
  ["Electric Glow"]: THREE.MeshStandardMaterial;
  ["Silk Glow"]: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(204,209,238)"]: THREE.MeshStandardMaterial;
  ["Perfect Tint"]: THREE.MeshStandardMaterial;
  ["California Dream"]: THREE.MeshStandardMaterial;
  ["Opaque(255,255,255)"]: THREE.MeshStandardMaterial;
  Autumn: THREE.MeshStandardMaterial;
  Windsurf: THREE.MeshStandardMaterial;
  ["Bright Idea"]: THREE.MeshStandardMaterial;
  ["Coastal Breeze"]: THREE.MeshStandardMaterial;
  ["True Love"]: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  Sienna: THREE.MeshStandardMaterial;
  Aura: THREE.MeshStandardMaterial;
  ["City Park"]: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  ["Opaque(185,185,185)"]: THREE.MeshStandardMaterial;
  ["Spanish Style"]: THREE.MeshStandardMaterial;
  ["Monte Carlo"]: THREE.MeshStandardMaterial;
  Namibia: THREE.MeshStandardMaterial;
  Uranus: THREE.MeshStandardMaterial;
  Arizona: THREE.MeshStandardMaterial;
  Impulse: THREE.MeshStandardMaterial;
  ["Butterfly Wing"]: THREE.MeshStandardMaterial;
  Hugo: THREE.MeshStandardMaterial;
  Porcelain: THREE.MeshStandardMaterial;
  ["Free Spirit"]: THREE.MeshStandardMaterial;
  ["Cozy Vibe"]: THREE.MeshStandardMaterial;
  ["Evening Glow"]: THREE.MeshStandardMaterial;
  Iris: THREE.MeshStandardMaterial;
  Lisbon: THREE.MeshStandardMaterial;
  ["Light Spirit"]: THREE.MeshStandardMaterial;
  Phoenix: THREE.MeshStandardMaterial;
  Bumblebee: THREE.MeshStandardMaterial;
  Freya: THREE.MeshStandardMaterial;
  Malibu: THREE.MeshStandardMaterial;
  ["Opaque(150,150,150)"]: THREE.MeshStandardMaterial;
  ["Opaque(50,50,50)"]: THREE.MeshStandardMaterial;
  ["Opaque(150,150,150)"]: THREE.MeshStandardMaterial;
  ["Opaque(110,110,110)"]: THREE.MeshStandardMaterial;
  ["Opaque(185,185,185)"]: THREE.MeshStandardMaterial;
  ["Harvest Time"]: THREE.MeshStandardMaterial;
  Aloha: THREE.MeshStandardMaterial;
  Victoria: THREE.MeshStandardMaterial;
  Spartacus: THREE.MeshStandardMaterial;
  ["Paradise Island"]: THREE.MeshStandardMaterial;
  ["Opaque(150,150,150)"]: THREE.MeshStandardMaterial;
  ["Opaque(110,110,110)"]: THREE.MeshStandardMaterial;
  ["Opaque(185,185,185)"]: THREE.MeshStandardMaterial;
  Hudson: THREE.MeshStandardMaterial;
  Adeline: THREE.MeshStandardMaterial;
  California: THREE.MeshStandardMaterial;
  Durango: THREE.MeshStandardMaterial;
  ["Floral Scent"]: THREE.MeshStandardMaterial;
  ["Opaque(51,51,51)"]: THREE.MeshStandardMaterial;
  ["Opaque(249,249,249)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  Melissa: THREE.MeshStandardMaterial;
  ["Opaque(0,128,0)"]: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(219,188,126)"]: THREE.MeshStandardMaterial;
  ["Opaque(87,173,113)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(219,188,126)"]: THREE.MeshStandardMaterial;
  ["Opaque(87,173,113)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(35,103,185)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Aztec: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,255,255)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  Columbia: THREE.MeshStandardMaterial;
  Argos: THREE.MeshStandardMaterial;
  ["Butterfly Bush"]: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  Galactica: THREE.MeshStandardMaterial;
  Abbey: THREE.MeshStandardMaterial;
  Luna: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,255,255)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  Zanzibar: THREE.MeshStandardMaterial;
  Aria: THREE.MeshStandardMaterial;
  Andorra: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  Zion: THREE.MeshStandardMaterial;
  Felicia: THREE.MeshStandardMaterial;
  Brimstone: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,255,255)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  Opera: THREE.MeshStandardMaterial;
  Haiti: THREE.MeshStandardMaterial;
  ["Country Breeze"]: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  ["Fairytale Dream"]: THREE.MeshStandardMaterial;
  ["Silk Elegance"]: THREE.MeshStandardMaterial;
  Alhambra: THREE.MeshStandardMaterial;
  ["Opaque(31,31,31)"]: THREE.MeshStandardMaterial;
  ["Opaque(178,178,178)"]: THREE.MeshStandardMaterial;
  Felix: THREE.MeshStandardMaterial;
  ["Opaque(165,173,178)"]: THREE.MeshStandardMaterial;
  ["Opaque(229,0,0)"]: THREE.MeshStandardMaterial;
  ["Plastic_-_Matte_(Black)"]: THREE.MeshStandardMaterial;
  Zoya: THREE.MeshStandardMaterial;
  Utah: THREE.MeshStandardMaterial;
  Venus: THREE.MeshStandardMaterial;
  Matrix: THREE.MeshStandardMaterial;
  ["Clear Day"]: THREE.MeshStandardMaterial;
  ["Opaque(191,191,191)"]: THREE.MeshStandardMaterial;
  ["Opaque(77,77,77)"]: THREE.MeshStandardMaterial;
  ["Opaque(187,197,203)"]: THREE.MeshStandardMaterial;
  Belize: THREE.MeshStandardMaterial;
  ["Beyond the Clouds"]: THREE.MeshStandardMaterial;
  Kathmandu: THREE.MeshStandardMaterial;
  ["Future Vision"]: THREE.MeshStandardMaterial;
  Nordic: THREE.MeshStandardMaterial;
  Volt: THREE.MeshStandardMaterial;
  Florida: THREE.MeshStandardMaterial;
  ["Opaque(64,64,64)"]: THREE.MeshStandardMaterial;
  ["Opaque(204,209,238)"]: THREE.MeshStandardMaterial;
  Montana: THREE.MeshStandardMaterial;
  ["Best of Summer"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  Bombay: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Arabella: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Chicago: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Pacific: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Herbal Scent"]: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Vienna: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Esprit: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Alvin: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["May Mist"]: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Ace: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Wellington: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Madagascar: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  Fiji: THREE.MeshStandardMaterial;
  ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(215,208,192)"]: THREE.MeshStandardMaterial;
  ["Opaque(211,214,211)"]: THREE.MeshStandardMaterial;
  ["Opaque(225,225,225)"]: THREE.MeshStandardMaterial;
  ["Opaque(155,96,80)"]: THREE.MeshStandardMaterial;
  Manchester: THREE.MeshStandardMaterial;
  ["Opaque(155,96,80)"]: THREE.MeshStandardMaterial;
  ["Opaque(225,225,225)"]: THREE.MeshStandardMaterial;
  Austin: THREE.MeshStandardMaterial;
  ["Opaque(155,96,80)"]: THREE.MeshStandardMaterial;
  ["Opaque(225,225,225)"]: THREE.MeshStandardMaterial;
  Nautico: THREE.MeshStandardMaterial;
  ["Opaque(155,96,80)"]: THREE.MeshStandardMaterial;
  ["Opaque(225,225,225)"]: THREE.MeshStandardMaterial;
  ["Gentle Touch"]: THREE.MeshStandardMaterial;
  ["Opaque(155,96,80)"]: THREE.MeshStandardMaterial;
  ["Opaque(225,225,225)"]: THREE.MeshStandardMaterial;
  Nevada: THREE.MeshStandardMaterial;
  ["Opaque(155,96,80)"]: THREE.MeshStandardMaterial;
  ["Opaque(225,225,225)"]: THREE.MeshStandardMaterial;
  ["Calm Balm"]: THREE.MeshStandardMaterial;
  ["Opaque(155,96,80)"]: THREE.MeshStandardMaterial;
  ["Opaque(225,225,225)"]: THREE.MeshStandardMaterial;
  Oxford: THREE.MeshStandardMaterial;
  ["Opaque(155,96,80)"]: THREE.MeshStandardMaterial;
  ["Opaque(225,225,225)"]: THREE.MeshStandardMaterial;
  ["Opaque(25,25,25)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(70,70,70)"]: THREE.MeshStandardMaterial;
  ["Breath of Spring"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
  ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
  ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
  ["Opaque(191,191,191)"]: THREE.MeshStandardMaterial;
  ["Opaque(10,10,10)"]: THREE.MeshStandardMaterial;
  ["Opaque(31,31,31)"]: THREE.MeshStandardMaterial;
  ["Opaque(178,178,178)"]: THREE.MeshStandardMaterial;
  ["Opaque(178,116,83)"]: THREE.MeshStandardMaterial;
  ["Opaque(31,31,31)"]: THREE.MeshStandardMaterial;
  ["Opaque(178,178,178)"]: THREE.MeshStandardMaterial;
  ["Opaque(63,63,63)"]: THREE.MeshStandardMaterial;
  ["Opaque(250,250,250)"]: THREE.MeshStandardMaterial;
  ["Opaque(160,160,160)"]: THREE.MeshStandardMaterial;
  Keira: THREE.MeshStandardMaterial;
  ["Opaque(0,128,0)"]: THREE.MeshStandardMaterial;
  ["Opaque(0,128,0)"]: THREE.MeshStandardMaterial;
  ["ABS_(White)"]: THREE.MeshStandardMaterial;
  ["Paint_-_Enamel_Glossy_(Grey)"]: THREE.MeshStandardMaterial;
  Tokyo: THREE.MeshStandardMaterial;
  ["Opaque(255,221,135)"]: THREE.MeshStandardMaterial;
  ["Opaque(25,25,25)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,242,232)"]: THREE.MeshStandardMaterial;
  ["Opaque(202,209,238)"]: THREE.MeshStandardMaterial;
  ["Opaque(0,128,0)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,221,135)"]: THREE.MeshStandardMaterial;
  ["Opaque(230,235,235)"]: THREE.MeshStandardMaterial;
  ["Opaque(230,235,235)"]: THREE.MeshStandardMaterial;
  Radar: THREE.MeshStandardMaterial;
  ["Opaque(1,60,210)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,255,255)"]: THREE.MeshStandardMaterial;
  ["Opaque(230,235,235)"]: THREE.MeshStandardMaterial;
  ["Dark Marmalade"]: THREE.MeshStandardMaterial;
  Lorenzo: THREE.MeshStandardMaterial;
  ["Light Aroma"]: THREE.MeshStandardMaterial;
  Monaco: THREE.MeshStandardMaterial;
  Canberra: THREE.MeshStandardMaterial;
  ["Opaque(255,221,135)"]: THREE.MeshStandardMaterial;
  ["Opaque(25,25,25)"]: THREE.MeshStandardMaterial;
  Colorado: THREE.MeshStandardMaterial;
  ["Opaque(255,221,135)"]: THREE.MeshStandardMaterial;
  ["Opaque(25,25,25)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,221,135)"]: THREE.MeshStandardMaterial;
  ["Opaque(25,25,25)"]: THREE.MeshStandardMaterial;
  ["Opaque(26,26,26)"]: THREE.MeshStandardMaterial;
  ["ABS_(White)_3"]: THREE.MeshStandardMaterial;
  ["Opaque(247,224,153)"]: THREE.MeshStandardMaterial;
  ["Urban Charm"]: THREE.MeshStandardMaterial;
  ["Paint_-_Enamel_Glossy_(Green)"]: THREE.MeshStandardMaterial;
  ["Steel_-_Satin"]: THREE.MeshStandardMaterial;
  ["Opaque(0,128,0)"]: THREE.MeshStandardMaterial;
  ["Steel_-_Satin"]: THREE.MeshStandardMaterial;
  ["Opaque(26,26,26)"]: THREE.MeshStandardMaterial;
  ["Paint_-_Enamel_Glossy_(Green)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,207,128)"]: THREE.MeshStandardMaterial;
  ["Opaque(0,128,0)"]: THREE.MeshStandardMaterial;
  ["Steel_-_Satin"]: THREE.MeshStandardMaterial;
  ["Opaque(87,173,113)"]: THREE.MeshStandardMaterial;
  ["Opaque(10,10,10)"]: THREE.MeshStandardMaterial;
  ["Acrylic_(Clear)"]: THREE.MeshStandardMaterial;
  ["Plastic_-_Matte_(Black)"]: THREE.MeshStandardMaterial;
  ["ABS_(White)_3"]: THREE.MeshStandardMaterial;
  ["Acrylic_(Clear)"]: THREE.MeshStandardMaterial;
  ["ABS_(White)_3"]: THREE.MeshStandardMaterial;
  ["ABS_(White)_1"]: THREE.MeshStandardMaterial;
  ["Steel_-_Satin"]: THREE.MeshStandardMaterial;
  ["Opaque(0,128,0)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,210,127)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,221,135)"]: THREE.MeshStandardMaterial;
  ["Steel_-_Satin"]: THREE.MeshStandardMaterial;
  ["Opaque(0,128,0)"]: THREE.MeshStandardMaterial;
  ["Opaque(255,210,127)"]: THREE.MeshStandardMaterial;
  ["Opaque(50,50,50)"]: THREE.MeshStandardMaterial;
  ["Opaque(0,128,0)"]: THREE.MeshStandardMaterial;
  ["Opaque(226,210,195)"]: THREE.MeshStandardMaterial;
  ["ABS_(White)"]: THREE.MeshStandardMaterial;
  ["Plastic_-_Matte_(Black)"]: THREE.MeshStandardMaterial;
  ["Steel_-_Satin"]: THREE.MeshStandardMaterial;
  ["ABS_(White)_1"]: THREE.MeshStandardMaterial;
  ["ABS_(White)_2"]: THREE.MeshStandardMaterial;
  ["Plastic_-_Glossy_(Black)"]: THREE.MeshStandardMaterial;
  ["Plastic_-_Glossy_(Black)"]: THREE.MeshStandardMaterial;
  ["Plastic_-_Glossy_(Black)"]: THREE.MeshStandardMaterial;
  ["ABS_(White)_3"]: THREE.MeshStandardMaterial;
  ["Plastic_-_Glossy_(Black)"]: THREE.MeshStandardMaterial;
};
